plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.jetbrains.kotlin.android)
    alias(libs.plugins.compose.compiler)
}

def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace 'com.movielist.tmdb'
    compileSdk = 37

    defaultConfig {
        applicationId "com.movielist.tmdb"
        minSdk 28
        targetSdk 36
        versionCode 3
        versionName "3.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    /*
    storeFile=app/keystore/keystore.jks
    storePassword=android
    keyAlias=android
    keyPassword=android
     */
    signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile = rootProject.file(keystoreProperties['storeFile'])
                storePassword = keystoreProperties['storePassword']
                keyAlias = keystoreProperties['keyAlias']
                keyPassword = keystoreProperties['keyPassword']
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        compose true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    implementation libs.core.ktx

    implementation libs.constraintlayout

    // Compose
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.ui
    implementation libs.androidx.ui.graphics
    implementation libs.androidx.ui.tooling.preview
    implementation libs.androidx.material3
    implementation libs.androidx.activity.compose
    implementation libs.coil.compose
    debugImplementation libs.androidx.ui.tooling
    debugImplementation libs.androidx.ui.test.manifest

    //Retrofit
    implementation libs.retrofit
    implementation libs.converter.gson
    implementation libs.converter.jackson
    //Glide
    implementation libs.glide

    // Padding / Margin
    implementation libs.sdp.android
    // Text Size
    implementation libs.ssp.android

    // Import the Firebase BoM
    implementation platform(libs.firebase.bom)

    // Admob
    implementation libs.play.services.ads


}
